In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr.size)
print(arr.dtype)
print(arr[0])

3
int32
1


In [6]:
# 0~4
a1=np.arange(5)
# 1로 초기화
a2=np.ones((2,2),dtype=str)
# 0으로 초기화
a3=np.zeros((3,3),dtype=int)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4]
[['1' '1']
 ['1' '1']]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
# 0~9까지 랜덤으로 초기화
a4 = np.random.randint(0,10,(4,4))
# 평균 0 , 표준편차 1로 초기화
a5 = np.random.normal(0,1,(4,4))

print(a4)
print(a5)

[[2 5 6 1]
 [3 8 7 6]
 [9 3 2 4]
 [3 5 9 6]]
[[ 0.10828513 -0.65825478 -0.03378059 -0.74747243]
 [-0.13165298 -1.52188955 -0.21617764 -1.32344056]
 [ 0.1735209   0.70602547  1.92689632  1.11778818]
 [-0.49668919 -0.58846454  1.89231723 -2.42917009]]


In [23]:
# 배열 합치기

a1 = np.array([1,2,3])
a2 = np.array([7,8,9])

# 가로로
a3 = np.concatenate([a1,a2])
print(a3)
a3 = np.hstack((a1,a2))
print(a3)

[1 2 3 7 8 9]
[1 2 3 7 8 9]


In [24]:
# 세로로
a4 = np.vstack((a1,a2))
print(a4)
a4 = np.dstack((a1,a2))
print(a4)

[[1 2 3]
 [7 8 9]]
[[[1 7]
  [2 8]
  [3 9]]]


In [25]:
# 형태 변형

a3=a3.reshape((3,2))
print(a3)

[[1 2]
 [3 7]
 [8 9]]


In [39]:
# 배열 나누기
arr = np.arange(8).reshape(2,4)
print(arr)

a1, a2 = np.split(arr,2,axis=0)
print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]]
[[4 5 6 7]]


In [40]:
a1, a2 = np.split(arr,2,axis=1)
print(a1)
print(a2)

[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


In [43]:
# 연산
print(arr+1)
print(arr*10)

[[1 2 3 4]
 [5 6 7 8]]
[[ 0 10 20 30]
 [40 50 60 70]]


In [46]:
# 배열끼리 연산
a1 = np.arange(16).reshape(4,4)
a2 = np.arange(4)
print(a1+a2)

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]


In [47]:
a2 = a2.reshape(4,1)
print(a1+a2)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]


In [55]:
# 체크하기
a1 = np.arange(16).reshape(4,4)

a2 = a1<10
print(a2)
a1[a2]=100
print(a1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [57]:
# 여러 함수
a1 = np.arange(16).reshape(4,4)

print(np.max(a1)) #최대
print(np.min(a1)) #최소
print(np.sum(a1)) #합
print(np.mean(a1)) #평균

15
0
120
7.5


In [62]:
print(a1)
print(np.sum(a1,axis=0))
print(np.sum(a1,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 28 32 36]
[ 6 22 38 54]


In [63]:
# 같은 간격으로 초기화
a1 = np.linspace(0,10,6)
print(a1)

# 시드 고정
np.random.seed(999)
print(np.random.randint(0,10,(1,5)))

# 중복 원소 제거
a2 = np.array([1,1,2,3,1,2,3,3,3])
print(np.unique(a2))

[ 0.  2.  4.  6.  8. 10.]
[[0 5 1 8 1]]
[1 2 3]


In [67]:
# 정렬
arr = np.array([4,7,5,6,9])
arr.sort()
print(arr) # 오름차순
print(arr[::-1]) # 내림차순

[4 5 6 7 9]
[9 7 6 5 4]


In [69]:
# 저장 , 불러오기
a1 = np.arange(0,5)
a2 = np.arange(5,10)
np.savez('saved.npz',array1=a1,array2=a2)

data=np.load('saved.npz')
r1 = data['array1']
r2 = data['array2']
print(r1)
print(r2)

[0 1 2 3 4]
[5 6 7 8 9]
